### PR TITLE
Fix panicking

### LINKED ISSUE #43: Panics if configuration is not set
There are panics that should be fixed.

The first one is in the `setup` method when trying to retrieve the `MaxRetryInterval` configuration when `c.config` is nil.
https://github.com/heetch/felice/blob/4aa9633649f00575adc667afb14331bebd65f760/consumer/consumer.go#L91

The second one is involved by fixing the first one: calling `setup` when `c.config` is nil won't create the `c.retryStrategy`. This ends with panic when using it in retry.StartWithCancel.
We should create the config before calling setup in the Serve method.
https://github.com/heetch/felice/blob/4aa9633649f00575adc667afb14331bebd65f760/consumer/consumer.go#L213

The third one is the `panic("unreachable")`, when sending SIGINT to the consumer, this piece of code is reachable. We should return a nil Message to close the consumer.
https://github.com/heetch/felice/blob/4aa9633649f00575adc667afb14331bebd65f760/consumer/consumer.go#L242

### PR DESCRIPTION
**Pull request by YassineE**
This PR fixes #43.

The first one is in the `setup` method when trying to retrieve the `MaxRetryInterval` configuration when `c.config` is nil.

The second one is involved by fixing the first one: calling `setup` when `c.config` is nil won't create the `c.retryStrategy`. This ends with panic when using it in `retry.StartWithCancel`.
We should create the config before calling `setup` in the `Serve` method.

The third one is the `panic("unreachable")`, when sending SIGINT to the consumer, this piece of code is reachable. We should return a nil Message to close the consumer.

### CODE REVIEW

File: consumer/consumer.go [hunk 1]
```diff
@@ -81,7 +81,7 @@ func (c *Consumer) setup() {
 		}
 	}
 
-	if c.retryStrategy == nil {
+	if c.config != nil && c.retryStrategy == nil {
```
Comment (tealeg) [inline consumer/consumer.go]: Are you sure this shouldn't be the following?:
```suggestion
	if c.config == nil || c.retryStrategy == nil {
```

Comment (YassineE) [reply consumer/consumer.go]: No it shouldn't. 

What we want here is to create the `retryStrategy` if it's not already done.

So we need the `MaxRetryInterval` which is coming from the config but we should assert that the it is not nil to avoid panicking.

Comment (tealeg) [reply consumer/consumer.go]: Yes, I see that.

My concern really is this: does the lack of config imply that we shouldn't create a retryStrategy?  Is this valid?

Comment (YassineE) [reply consumer/consumer.go]: The thing is from where should we get the `MaxDelay` value if we don't have a config?

**Comment by YassineE** [comment]
@rogpeppe it is a fair point and thank you for that.

IIRC the purpose was to have the Consumer's zero value usable but as you said it is very easy to make mistakes because it needs some configuration to be usable. 

I propose to create an issue and discuss about it over there.

**Comment by tealeg** [comment]
> This change looks OK, I think, but I'm not entirely sure - ISTM that the initialization code could be a bit clearer.
> 
> I don't think it's easy to fix without breaking backward compatibility, but ISTM that the way that Consumer is created and configured makes it very easy to make this kind of mistake. Currently AFAICS you are expected to create an instance of the Consumer yourself and optionally populate some of the fields. Other fields are filled in when you call Consumer.Serve. If there was a single entry constructor function for the Consumer which received a Config value and returned a new ready-to-use Consumer, all the code could rely on having correctly set up configuration.
> 
> I don't really understand the distinction between the different kinds of config parameters. Why are Logger and Metrics fields inside the Consumer, not inside Config?. By putting Config as an argument to Serve, we're ensuring that the Handle method can't see any of that configuration, which might not be an issue now, but might be later.

These are excellent points - they probably deserve to be addressed separately.  Fancy raising an issue @rogpeppe ?  In the context of `felice`, I think its still safe to make those kinds of breaking changes (especially considering the general approach to dependency management via vendoring in Go projects).

**Comment by YassineE** [comment]
I created an issue https://github.com/heetch/felice/issues/44

**Comment by YassineE** [comment]
@rogpeppe @tealeg I created an issue https://github.com/heetch/felice/issues/44

File: consumer/consumer.go (hunk 1 above)
Comment (YassineE) [reply consumer/consumer.go]: @tealeg 🆙 ?
